name: GitLeaks
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:latest
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}